/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;

/**
 *
 * @author AMSA Damruwan
 */
public class Enter extends javax.swing.JFrame {
    String date;
    int timeRun=0;
    DBO dbo=new DBO();
    /**
     * Creates new form Enter
     */
    public Enter() {
        initComponents();
         new Thread(){
           public void run(){
               while(timeRun==0){
                   Calendar cal=new GregorianCalendar();
                   int hour=cal.get(Calendar.HOUR);
                   int min=cal.get(Calendar.MINUTE);
                   int sec=cal.get(Calendar.SECOND);
                   int am_pm=cal.get(Calendar.AM_PM);
                   String day_night="";
                   if(am_pm==1){
                      day_night="PM";
                   }
                   else{
                      day_night="AM";
                   }
                   String time=hour+":"+min+":"+sec+" "+day_night;
                   desktopclock.setText(time);
               }
           }
           
        }
        .start(); 
         loadDate();
    }
    
    
    void loadDate(){
        DateTime dat1=new DateTime();
        date = dbo.getDate();
        desktopdate.setText(date);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Enter = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desktopclock = new javax.swing.JLabel();
        desktopdate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        Enter.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        Enter.setText(">>>");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        jPanel1.add(Enter);
        Enter.setBounds(200, 621, 130, 50);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 100)); // NOI18N
        jLabel2.setText("OSPITAL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 110, 410, 101);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 60)); // NOI18N
        jLabel1.setText("MANAGEMENT ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(650, 210, 530, 93);

        desktopclock.setFont(new java.awt.Font("Digital-7 Mono", 0, 36)); // NOI18N
        desktopclock.setText("00:00:00 00");
        jPanel1.add(desktopclock);
        desktopclock.setBounds(1200, 60, 180, 50);

        desktopdate.setFont(new java.awt.Font("Digital-7 Mono", 0, 24)); // NOI18N
        desktopdate.setText("0000-00-00");
        jPanel1.add(desktopdate);
        desktopdate.setBounds(1200, 30, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 60)); // NOI18N
        jLabel4.setText("SYSTEM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 340, 330, 61);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/icon-medical_advice.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1010, 270, 370, 410);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/blue-hospital-sign-icon-10.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 30, 230, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/global_health-512.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 10, 550, 480);

        jLabel9.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel9.setText("ENTER");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 630, 150, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/add_friend-512.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 220, 490, 470);

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/HD Sanju _ (268).jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 1370, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
         MainPage MP=new MainPage();
             MP.setVisible(true);
             MP.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
             this.dispose();
    }//GEN-LAST:event_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Enter;
    private javax.swing.JLabel desktopclock;
    private javax.swing.JLabel desktopdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
